{
 "title": "BugSelectorTraining",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "BugSelectorTraining incoming queue wait times",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(1.0, sum(rate(BugSelectorTraining_incoming_latency_bucket[15s])) by (le))",
     "legendFormat": "Max"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(BugSelectorTraining_incoming_latency_bucket[15s])) by (le))",
     "legendFormat": "95th quantile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(BugSelectorTraining_incoming_latency_bucket[15s])) by (le))",
     "legendFormat": "Median"
    },
    {
     "expr": "histogram_quantile(0.1, sum(rate(BugSelectorTraining_incoming_latency_bucket[15s])) by (le))",
     "legendFormat": "Fastest 10%"
    }
   ]
  },
  {
   "title": "Loss",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "delta(BugSelectorTraining_training_loss_sum[1m]) / delta(BugSelectorTraining_training_loss_count[1m])",
     "legendFormat": "Training loss"
    }
   ]
  },
  {
   "title": "Message count ",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "BugSelectorTraining_incoming_messages_total",
     "legendFormat": "Incoming messages"
    }
   ]
  },
  {
   "title": "Data queue size",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "BugSelectorTraining_training_queue"
    }
   ]
  },
  {
   "title": "Models published",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "BugSelectorTraining_models_published_total",
     "legendFormat": "Incoming messages"
    }
   ]
  }
 ]
}