{
 "title": "BugDetectorTraining",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "BugDetectorTraining incoming queue wait times",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(1.0, sum(rate(BugDetectorTraining_incoming_latency_bucket[15s])) by (le))",
     "legendFormat": "Max"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(BugDetectorTraining_incoming_latency_bucket[15s])) by (le))",
     "legendFormat": "95th quantile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(BugDetectorTraining_incoming_latency_bucket[15s])) by (le))",
     "legendFormat": "Median"
    },
    {
     "expr": "histogram_quantile(0.1, sum(rate(BugDetectorTraining_incoming_latency_bucket[15s])) by (le))",
     "legendFormat": "Fastest 10%"
    }
   ]
  },
  {
   "title": "Loss",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(BugDetectorTraining_training_loss_sum[1m]) / delta(BugDetectorTraining_training_loss_count[1m])",
     "legendFormat": "Training loss"
    },
    {
     "expr": "delta(BugDetectorTraining_validation_loss_sum[1m]) / delta(BugDetectorTraining_validation_loss_count[1m])",
     "legendFormat": "Validation loss"
    }
   ]
  },
  {
   "title": "Message count ",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "BugDetectorTraining_incoming_messages_total",
     "legendFormat": "Incoming messages"
    },
    {
     "expr": "BugDetectorTraining_incoming_graphs_total",
     "legendFormat": "Incoming graphs"
    }
   ]
  },
  {
   "title": "Replay buffer in-memory queue",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "BugDetectorTraining_replay_buffer_incoming_queue"
    }
   ]
  },
  {
   "title": "Published graphs",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "BugDetectorTraining_parameter_updates_total",
     "legendFormat": "Published graphs"
    }
   ]
  }
 ]
}