{
 "title": "DetectorDataScoringWorker",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "DetectorDataScoringWorker incoming queue wait times",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(1.0, sum(rate(DetectorDataScoringWorker_incoming_latency_bucket[15s])) by (le))",
     "legendFormat": "Max"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(DetectorDataScoringWorker_incoming_latency_bucket[15s])) by (le))",
     "legendFormat": "95th quantile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(DetectorDataScoringWorker_incoming_latency_bucket[15s])) by (le))",
     "legendFormat": "Median"
    },
    {
     "expr": "histogram_quantile(0.1, sum(rate(DetectorDataScoringWorker_incoming_latency_bucket[15s])) by (le))",
     "legendFormat": "Fastest 10%"
    }
   ]
  },
  {
   "title": "DetectorDataScoringWorker processing time",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(1.0, sum(rate(DetectorDataScoringWorker_processing_time_bucket[15s])) by (le))",
     "legendFormat": "Max"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(DetectorDataScoringWorker_processing_time_bucket[15s])) by (le))",
     "legendFormat": "95th quantile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(DetectorDataScoringWorker_processing_time_bucket[15s])) by (le))",
     "legendFormat": "Median"
    },
    {
     "expr": "histogram_quantile(0.1, sum(rate(DetectorDataScoringWorker_processing_time_bucket[15s])) by (le))",
     "legendFormat": "Fastest 10%"
    }
   ]
  },
  {
   "title": "DetectorDataScoringWorker outgoing queue wait times",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(1.0, sum(rate(DetectorDataScoringWorker_outgoing_latency_bucket[15s])) by (le))",
     "legendFormat": "Max"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(DetectorDataScoringWorker_outgoing_latency_bucket[15s])) by (le))",
     "legendFormat": "95th quantile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(DetectorDataScoringWorker_outgoing_latency_bucket[15s])) by (le))",
     "legendFormat": "Median"
    },
    {
     "expr": "histogram_quantile(0.1, sum(rate(DetectorDataScoringWorker_outgoing_latency_bucket[15s])) by (le))",
     "legendFormat": "Fastest 10%"
    }
   ]
  },
  {
   "title": "Message count ",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "DetectorDataScoringWorker_incoming_messages_total",
     "legendFormat": "Incoming messages"
    },
    {
     "expr": "DetectorDataScoringWorker_outgoing_messages_total",
     "legendFormat": "Outgoing messages"
    }
   ]
  },
  {
   "title": "Data queue size",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DetectorDataScoringWorker_data_queue"
    }
   ]
  }
 ]
}