{
 "title": "Message counters",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "BugSelectorServer",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "BugSelectorServer_incoming_messages_total",
     "legendFormat": "Incoming"
    },
    {
     "expr": "BugSelectorServer_outgoing_messages_total",
     "legendFormat": "Outgoing"
    }
   ]
  },
  {
   "title": "DetectorDataScoringWorker",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DetectorDataScoringWorker_incoming_messages_total",
     "legendFormat": "Incoming"
    },
    {
     "expr": "DetectorDataScoringWorker_outgoing_messages_total",
     "legendFormat": "Outgoing"
    }
   ]
  },
  {
   "title": "BugDetectorTraining Incoming",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "BugDetectorTraining_incoming_messages_total",
     "legendFormat": "Incoming"
    }
   ]
  },
  {
   "title": "BugSelectorTraining Incoming",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "BugSelectorTraining_incoming_messages_total",
     "legendFormat": "Incoming"
    }
   ]
  },
  {
   "title": "DataGeneratingPipelineCoordinator packages finished",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DataGeneratingPipelineCoordinator_published_packages_total",
     "legendFormat": "Incoming"
    }
   ]
  }
 ]
}