{
 "title": "BugLab Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Bug Detector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Loss",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(BugDetectorTraining_training_loss_sum[20m]) / delta(BugDetectorTraining_training_loss_count[20m])",
     "legendFormat": "Training"
    },
    {
     "expr": "delta(BugDetectorTraining_validation_loss_sum[20m]) / delta(BugDetectorTraining_validation_loss_count[20m])",
     "legendFormat": "Validation"
    }
   ]
  },
  {
   "title": "Incoming Graphs",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(DetectorTrainingDataBuffer_incoming_graphs_total[5m]))*60",
     "legendFormat": "5m"
    }
   ]
  },
  {
   "title": "Data Buffer",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(DetectorTrainingDataBuffer_incoming_graphs_total[1m])*60",
     "legendFormat": "Incoming Graphs"
    },
    {
     "expr": "rate(DetectorTrainingDataBuffer_replay_buffer_incoming_queue[1m])*60",
     "legendFormat": "Buffer Input"
    }
   ]
  },
  {
   "title": "Parameter Updates/hour",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(BugDetectorTraining_parameter_updates_total[1h]))*60 *60",
     "legendFormat": "updates/hour"
    }
   ]
  },
  {
   "title": "Incoming Training Queue Size",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "DetectorTrainingDataBuffer_replay_buffer_incoming_queue",
     "legendFormat": "Queue Size"
    }
   ]
  },
  { "title": "Bug Selector Model", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Loss",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(BugSelectorTraining_training_loss_sum[5m]) / delta(BugSelectorTraining_training_loss_count[5m])",
     "legendFormat": "Loss"
    }
   ]
  },
  {
   "title": "Training Queue Load",
   "type": "gauge",
   "description": "Load in Messages per second",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(BugSelectorTraining_incoming_messages_total[5m])*60",
     "legendFormat": "msg/min"
    }
   ]
  },
  {
   "title": "Parameter Updates/10min",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(BugSelectorTraining_models_published_total[1h])*60*10",
     "legendFormat": "per 10min"
    }
   ]
  },
  {
   "title": "Detector Scoring Worker",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(DetectorDataScoringWorker_incoming_messages_total[2m]) * 60",
     "legendFormat": "samples/min in"
    },
    {
     "expr": "rate(DetectorDataScoringWorker_outgoing_messages_total[2m]) * 60",
     "legendFormat": "samples/min Out"
    }
   ]
  },
  {
   "title": "Selector Training Queue Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "BugSelectorTraining_training_queue",
     "legendFormat": "Training Queue Size"
    }
   ]
  },
  {
   "title": "BugSelectorServer",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(BugSelectorServer_incoming_latency_bucket[5m])) by (le))",
     "legendFormat": "95% Latency "
    },
    {
     "expr": "rate(BugSelectorServer_outgoing_messages_total[1m]) * 60",
     "legendFormat": "Samples/Min Out"
    },
    {
     "expr": "rate(BugSelectorServer_incoming_messages_total[2m]) * 60",
     "legendFormat": "Samples/Min In"
    }
   ]
  },
  {
   "title": "BugSelector rqs/sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(BugSelectorServer_outgoing_messages_total[2m])",
     "legendFormat": "req/sec"
    }
   ]
  },
  {
   "title": "Bug Selector Entropy",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "BugSelectorServer_selection_entropy",
     "legendFormat": "Entropy"
    }
   ]
  },
  {
   "title": "Data Generating Pipeline packages finished",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "DataGeneratingPipelineCoordinator_published_packages_total",
     "legendFormat": "Consumed Packages"
    }
   ]
  },
  {
   "title": "Samples Published from Active Workers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(BuggyDataCreator_samples_published_total)"
    }
   ]
  }
 ]
}